# values for airqo-device-registry-api.
env:
  deployment_name: airqo-stage-device-registry-api
  service_name: airqo-stage-device-registry-api-svc
  labels: sta-dev-reg-api
  secret: env-device-registry-staging

replicaCount: 2

image:
  repository: us.gcr.io/airqo-250220/airqo-stage-device-registry-api
  tag: latest
  pullPolicy: Always
  readinessProbe:
    httpGet:
      path: /ready
      port: 3000
    initialDelaySeconds: 5
    periodSeconds: 30
  livenessProbe:
    httpGet:
      path: /live
      port: 3000
    initialDelaySeconds: 20
    periodSeconds: 60

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  nodePort: 31002
  targetPort: 3000
  port: 3000

ingress:
  enabled: false

nodeSelector: {}
resources: {}
affinity: {}
torelations: {}


## Application level settings  
appMode: staging