{{- range $topic := .Values.topics }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ $topic.name }}
  namespace: {{ $topic.namespace }}
  labels:
    strimzi.io/cluster: {{ $topic.cluster }}
spec:
  topicName: {{ $topic.name }}
  partitions: {{ $topic.partitions }}
  replicas: {{ $topic.replicas }}
  config:
    retention.ms: {{ $topic.retention }}
{{- end}}
