###########################################################
# Start deployment of locate api
###########################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airqo-locate-api
  namespace: production
spec:
  selector:
    matchLabels:
      app: locate-api
  replicas: 2
  template:
    metadata:
      labels:
        app: locate-api
    spec:
      containers:
        - name: locate-api
          image: us.gcr.io/airqo-250220/airqo-locate-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4001
              name: locate-api
          env:
            - name: GET_HOSTS_FROM
              value: dns
            - name: MONGO_GCE_URI
              valueFrom:
                secretKeyRef:
                  name: prod-locate-secret
                  key: MONGO_GCE_URI
            - name: DB_NAME_PROD
              valueFrom:
                secretKeyRef:
                  name: prod-locate-secret
                  key: PLATFORM_MONGO_PROD
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: prod-locate-secret
                  key: SECRET_KEY

---
kind: Service
apiVersion: v1
metadata:
  name: airqo-locate-api-svc
  namespace: production
spec:
  selector:
    app: locate-api
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001
      nodePort: 30004
  type: NodePort
