###########################################################
# Start deployment of device registry api - Staging
###########################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airqo-stage-device-registry-api
  namespace: staging
spec:
  selector:
    matchLabels:
      app: sta-device-reg-api
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: sta-device-reg-api
    spec:
      containers:
        - name: sta-dev-reg-api
          image: us.gcr.io/airqo-250220/airqo-stage-device-registry-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: sta-dev-reg-api
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 3000
          #   initialDelaySecond: 5
          #   periodSeconds: 3
          #   successThreshold: 1
          env:
            - name: GET_HOSTS_FROM
              value: dns
            - name: MONGO_GCE_URI
              valueFrom:
                secretKeyRef:
                  name: stage-device-reg-secret
                  key: MONGO_GCE_URI
            - name: MONGO_PROD
              valueFrom:
                secretKeyRef:
                  name: stage-device-reg-secret
                  key: MONGO_PROD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: stage-device-reg-secret
                  key: JWT_SECRET
            - name: MONGO_DEV
              valueFrom:
                secretKeyRef:
                  name: stage-device-reg-secret
                  key: MONGO_DEV
            - name: MONGO_STAGE
              valueFrom:
                secretKeyRef:
                  name: stage-device-reg-secret
                  key: MONGO_STAGE
            - name: MAIL_PASS
              valueFrom:
                secretKeyRef:
                  name: stage-device-reg-secret
                  key: MAIL_PASS
            - name: MAIL_USER
              valueFrom:
                secretKeyRef:
                  name: stage-device-reg-secret
                  key: MAIL_USER
            - name: LOCAL_DB
              valueFrom:
                secretKeyRef:
                  name: stage-device-reg-secret
                  key: LOCAL_DB

---
kind: Service
apiVersion: v1
metadata:
  name: airqo-stage-device-registry-api-svc
  namespace: staging
spec:
  selector:
    app: sta-device-reg-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31002
  type: NodePort
